name: daily-cron
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"batchLength": 1, "deleteAfter": false}' \
          -H 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}' \
          https://logdrain-app.vercel.app/api/cron